'use strict';
// Customer-facing Chef NARA layer: conversation UX and order-building shortcuts.
(function(){
 const dialog=document.querySelector('#guide-dialog');if(!dialog)return;
 const labels={de:{eyebrow:'👨‍🍳 CHEF NARA · DEIN BESTELL-PARTNER',welcome:'Ich stelle dir dein komplettes NARA-Erlebnis zusammen. Sag mir Geschmack, Personen und Budget – ich schlage passende Extras vor.',title:'Chef-Schnellwahl',menu:'Komplettes Menü',surprise:'Überrasch mich',share:'Zum Teilen',menuText:'Ich möchte ein komplettes Menü mit Getränk und Beilage',surpriseText:'Überrasche mich mit einer passenden Kombination',shareText:'Wir sind mehrere Personen und möchten teilen'},en:{eyebrow:'👨‍🍳 CHEF NARA · YOUR ORDER PARTNER',welcome:'I will build your complete NARA experience. Tell me your taste, group size and budget – I will suggest suitable extras.',title:'Chef quick choices',menu:'Complete menu',surprise:'Surprise me',share:'For sharing',menuText:'I want a complete meal with a drink and side',surpriseText:'Surprise me with a suitable combination',shareText:'We are several people and want to share'},ar:{eyebrow:'👨‍🍳 الشيف نارا · شريك طلبك',welcome:'سأجهز لك تجربة NARA كاملة. أخبرني بذوقك وعدد الأشخاص والميزانية، وسأقترح الإضافات المناسبة.',title:'اختيارات الشيف السريعة',menu:'وجبة كاملة',surprise:'فاجئني',share:'للمشاركة',menuText:'أريد وجبة كاملة مع مشروب وإضافة',surpriseText:'فاجئني بتوليفة مناسبة',shareText:'نحن عدة أشخاص ونريد أطباقاً للمشاركة'}};
 const update=()=>{const l=labels[typeof guideLanguage==='function'?guideLanguage():'de']||labels.de;const eyebrow=dialog.querySelector('.eyebrow');if(eyebrow)eyebrow.textContent=l.eyebrow;const welcome=dialog.querySelector('.chef-welcome');if(welcome)welcome.textContent=l.welcome;const box=dialog.querySelector('.chef-shortcuts');if(box){box.querySelector('span').textContent=l.title;const bs=box.querySelectorAll('button');[l.menu,l.surprise,l.share].forEach((x,i)=>{if(bs[i])bs[i].textContent=x});bs[0]?.setAttribute('data-chef-text',l.menuText);bs[1]?.setAttribute('data-chef-text',l.surpriseText);bs[2]?.setAttribute('data-chef-text',l.shareText)}};
 const chat=dialog.querySelector('#guide-chat');if(chat&&!chat.dataset.chef){chat.dataset.chef='1';const p=chat.querySelector('.assistant-bubble');if(p)p.classList.add('chef-welcome')}
 const choices=dialog.querySelector('.fire-choices');if(choices&&!dialog.querySelector('.chef-shortcuts')){const box=document.createElement('div');box.className='chef-shortcuts';box.innerHTML='<span></span><button type="button"></button><button type="button"></button><button type="button"></button>';choices.after(box);box.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const input=dialog.querySelector('#guide-prompt');input.value=b.dataset.chefText;dialog.querySelector('#find-fire-match')?.click()})}update();document.addEventListener('nara-language-changed',update);
})();
