'use strict';
(function(){let stage='PREPARE',selected=null,orders=[],liveMode='active';const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),money=c=>(Number(c||0)/100).toFixed(2)+' €';document.querySelectorAll('.side-nav button').forEach((b,i)=>b.title=['الصفحة الرئيسية','الطلبات قيد التحضير','طلبات التسليم','التقارير','الإعدادات','إعدادات النظام'][i]||'قائمة');
function normalize(o){const t=String(o.rawText||''),code=o.externalOrderCode||((t.match(/#([A-Z0-9]{5,12})\b/i)||[])[1]||'');if(!t||!code)return o;const start=t.lastIndexOf('#'+code),end=t.indexOf('Print order',start)>start?t.indexOf('Print order',start):t.length,seg=t.slice(start,end).replace(/\s+/g,' ').trim();const phone=(seg.match(/(\+\d{8,15})/)||[])[1]||'',head=(seg.match(/(\d{5})\s+([^,]+),\s*([^#]+?)\s+#/i)||[]),person=(seg.match(/Delivery\s+([A-ZÄÖÜ][A-Za-zÄÖÜäöüß]+(?:\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß]+)+)\s+\+\d/i)||[])[1]||'';const items=[];for(const m of seg.matchAll(/(?:^|\s)(\d+)\s+([A-Za-zÄÖÜäöüß0-9][^€]{2,90}?)\s+EUR\s*([0-9]+[,.][0-9]{2})/gi)){let name=m[2].replace(/^(?:Online|Burger|Specials|Dips|Falafel|Sandwiches|Salate|Hot Dogs|Alkoholfreie Getränke|Chicken Buckets & Deals \(New\))\s+/i,'').trim();if(!/^(subtotal|total|delivery fee)$/i.test(name))items.push({name,quantity:+m[1],unitCents:Math.round(Number(m[3].replace(',','.'))*100)/+m[1]})}if(items.length)o.cart=items;o.externalOrderCode=code;o.delivery={...(o.delivery||{}),name:o.delivery?.name||person,phone:o.delivery?.phone||phone,postal:o.delivery?.postal||head[1]||'',city:o.delivery?.city||head[2]?.trim()||'',street:o.delivery?.street||head[3]?.trim()||''};const total=(seg.match(/Total\s+(?:EUR|€)\s*([0-9]+[,.][0-9]{2})/i)||[])[1];if(total)o.externalTotalCents=Math.round(Number(total.replace(',','.'))*100);return o}
function stageOf(o){const st=String(o.status||'').toUpperCase();return st==='COMPLETED'||st==='CANCELLED'?'DONE':(o.liveStage||'PREPARE')}function stageLabel(s){return ({PREPARE:'بالتحضير',HANDOVER:'عند موظف التوصيل',DONE:'تم التسليم'})[s]||'بالتحضير'}function source(o){return String(o.source||o.platform||'NARA').toUpperCase()}
function enrichOrder(o){if(!o.rawText)return o;const text=String(o.rawText).replace(/\s+/g,' '),d=o.delivery||{},m=text.match(/(\d{5})\s+([^,]+),\s*([\p{L}.-]+(?:straße|strasse|weg|platz|allee|ring|gasse))\s+(\d+[a-zA-Z]?)/iu),name=text.match(/\d+[a-zA-Z]?\s+([\p{L}]+(?:\s+[\p{L}]+)+)\s+(?:ASAP|Scheduled|Delivery)/iu),phone=text.match(/(\+\d{8,15})/);if(m)o.delivery={...d,postal:m[1]||d.postal,city:m[2].trim()||d.city,street:m[3]||d.street,house:m[4]||d.house};if(name)o.delivery={...(o.delivery||d),name:name[1].trim()||d.name};if(phone)o.delivery={...(o.delivery||d),phone:d.phone||phone[1]};return o}
async function load(){try{const r=await fetch('/api/kasse-state',{cache:'no-store'});if(r.ok){const d=await r.json(),today=new Date().toISOString().slice(0,10),query=(document.querySelector('#live-archive-search')?.value||'').trim().toLowerCase();orders=(d.orders||[]).filter(o=>o.source||o.platform).filter(o=>liveMode==='archive'?o.liveArchivedAt:!o.liveArchivedAt&&String(o.createdAt||o.orderDate||'').slice(0,10)===today).filter(o=>!query||[o.externalOrderCode,o.displayCode,o.delivery?.name,o.delivery?.street,o.delivery?.city,o.rawText].some(v=>String(v||'').toLowerCase().includes(query))).map(normalize).map(enrichOrder);if(selected)selected=orders.find(x=>String(x.id)===String(selected.id))||selected}}catch{}render()}
function render(){['PREPARE','HANDOVER','DONE'].forEach(s=>$('#count-'+s.toLowerCase()).textContent=orders.filter(o=>stageOf(o)===s).length);const list=orders.filter(o=>stageOf(o)===stage);$('#order-list').innerHTML=list.map(o=>'<article class="order-card '+(selected?.id===o.id?'selected':'')+'" data-id="'+esc(o.id)+'"><div class="timer">ASAP</div><div><h3>'+esc([o.delivery?.postal,o.delivery?.city].filter(Boolean).join(' '))+' '+esc([o.delivery?.street,o.delivery?.house].filter(Boolean).join(' '))+'</h3><p>'+esc(o.delivery?.name||'Kunde')+'</p><p>● #'+esc(o.externalOrderCode||o.displayCode||o.id)+'</p></div><div class="source">'+esc(source(o))+'</div></article>').join('')||'<p>Keine Aufträge in dieser Ansicht.</p>';document.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>{selected=orders.find(o=>String(o.id)===x.dataset.id);renderDetail();render()});renderDetail();$('#sync-status').textContent=(liveMode==='archive'?'Archiv · ':'Live synchronisiert · ')+new Date().toLocaleTimeString('de-DE')}
function renderDetail(){const o=selected;if(!o){$('#order-detail').innerHTML='<p>Wähle einen Auftrag aus.</p>';return}const cart=o.cart||[],d=o.delivery||{},current=stageOf(o);$('#order-detail').innerHTML='<div class="detail-head"><div><h2>'+esc([d.postal,d.city].filter(Boolean).join(' '))+' '+esc([d.street,d.house].filter(Boolean).join(' '))+'</h2><div class="detail-meta">#'+esc(o.externalOrderCode||o.displayCode||o.id)+' · Delivery · '+esc(source(o))+'</div></div><div class="source">'+esc(String(o.status||'').toUpperCase()==='CANCELLED'?'ملغي من المنصة':stageLabel(current))+'</div></div><div class="detail-contact"><b>'+esc(d.name||'Kunde')+'</b><br>'+esc(d.phone||'')+'<br>'+esc([d.street,d.house,d.postal,d.city].filter(Boolean).join(' '))+'</div><h3>'+cart.reduce((n,x)=>n+Number(x.quantity||0),0)+' Items</h3>'+cart.map(x=>'<div class="item"><span>'+x.quantity+' '+esc(x.name)+'<small>'+esc(x.note||'')+'</small></span><b>'+money(Number(x.unitCents||0)*Number(x.quantity||0))+'</b></div>').join('')+'<div class="total"><span>Total</span><span>'+money(o.externalTotalCents||cart.reduce((s,x)=>s+Number(x.unitCents||0)*Number(x.quantity||0),0))+'</span></div><div class="actions"><button class="secondary" onclick="window.print()">🖨 Print order</button><button class="primary" id="advance">'+(current==='PREPARE'?'تسليم للموظف':'تم التسليم')+'</button></div>';$('#advance')?.addEventListener('click',async()=>{const next=current==='PREPARE'?'HANDOVER':'DONE';try{const r=await fetch('/api/live-orders/stage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:o.id,stage:next})}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||r.status);Object.assign(o,j.order||{liveStage:next})}catch(e){alert('تعذر حفظ الحالة: '+e.message);return}load()})}
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;document.querySelectorAll('[data-stage]').forEach(x=>x.classList.toggle('active',x===b));render()});const bar=document.querySelector('.toolbar'),sync=$('#sync-status');if(bar&&!$('#platform-filter')){const label=document.createElement('label');label.className='platform-label';label.innerHTML='Platform <select id="platform-filter"><option value="ALL">Alle Plattformen</option><option value="LIEFERANDO">Lieferando</option><option value="WOLT">Wolt</option><option value="UBER_EATS">Uber Eats</option><option value="LANCH">Lanch</option><option value="NARA">NARA / intern</option></select>';bar.insertBefore(label,sync);$('#platform-filter').onchange=()=>{const v=$('#platform-filter').value;document.querySelectorAll('.order-card').forEach(c=>{const badge=c.querySelector('.source');c.style.display=v==='ALL'||(badge&&badge.textContent.trim()===v)?'':'none'});const chosen=orders.find(o=>source(o)===v);if(v!=='ALL'&&chosen){selected=chosen;renderDetail()}}}if(bar&&!$('#live-archive-tools')){const tools=document.createElement('span');tools.id='live-archive-tools';tools.innerHTML='<input id="live-archive-search" placeholder="بحث بالأرشيف أو الطلب" style="margin-inline:8px;padding:7px"><button id="live-archive-toggle" type="button">عرض الأرشيف</button><button id="live-archive-day" type="button">أرشفة اليوم</button>';bar.appendChild(tools);$('#live-archive-search').oninput=load;$('#live-archive-toggle').onclick=()=>{liveMode=liveMode==='archive'?'active':'archive';$('#live-archive-toggle').textContent=liveMode==='archive'?'عرض طلبات اليوم':'عرض الأرشيف';selected=null;load()};$('#live-archive-day').onclick=async()=>{const r=await fetch('/api/live-orders/archive-day',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:new Date().toISOString().slice(0,10)})});const j=await r.json();alert(r.ok?'تمت أرشفة '+j.archivedCount+' طلبات':j.error||'تعذر الأرشفة');load()}}load();setInterval(load,5000)})();
/* Live Orders detail/timeline enhancement */
(function(){
  const esc2=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
  const euro2=v=>(Number(v||0)/100).toFixed(2)+' €';
  function parsed(o){
    const raw=String(o.rawText||''); const code=o.externalOrderCode||''; if(!raw||!code)return o;
    const at=raw.lastIndexOf('#'+code), end0=raw.indexOf('Print order',at); const seg=(at>=0?raw.slice(at,end0>at?end0:raw.length):raw).replace(/\s+/g,' ').trim();
    const accepted=(seg.match(/Order accepted at\s+([^#]+?)(?=\s+\d+\s+Items|\s+Items)/i)||[])[1]||'';
    const verify=(seg.match(/Verification code:\s*(\d{4,12})/i)||[])[1]||'';
    const addr=(seg.match(/(\d{5})\s+([^,]+),\s*([^#]+?)\s+#/i)||[]);
    const phone=(seg.match(/(\+\d{8,15})/)||[])[1]||'';
    const blockStart=seg.search(/\b\d+\s+Items\b/i), sub=seg.search(/\bSubtotal\b/i); const block=blockStart>=0?seg.slice(blockStart,sub>blockStart?sub:seg.length):'';
    const items=[]; for(const m of block.matchAll(/(?:^|\s)(\d+)\s+([^€]{2,90}?)\s+EUR\s*([\d]+[,.][\d]{2})/gi)){const n=m[2].trim();if(!/^(subtotal|total|delivery fee|order accepted|verification code)/i.test(n))items.push({name:n.replace(/^Online\s+/i,''),quantity:+m[1],unitCents:Math.round(Number(m[3].replace(',','.'))*100)/+m[1]})}
    o.__detail={accepted,verify,phone,postal:addr[1]||o.delivery?.postal||'',city:(addr[2]||o.delivery?.city||'').trim(),street:(addr[3]||o.delivery?.street||'').trim(),items}; return o;
  }
  function timeline(o){const d=o.__detail||{};const accepted=d.accepted||o.acceptedAt||o.createdAt||o.receivedAt||'';const eta=o.estimatedDeliveryTime||o.eta||o.delivery?.eta||o.expectedAt||'';return '<div class="timeline"><div><b>استلام الطلب</b><span>'+esc2(accepted||'—')+'</span></div><div><b>المرحلة الحالية</b><span>'+esc2(o.liveStage||'PREPARE')+'</span></div><div><b>الوقت المتوقع</b><span>'+esc2(eta||'حسب المنصة')+'</span></div></div>'}
  async function refreshDetail(){const card=document.querySelector('.order-card.selected');if(!card)return;const code=(card.textContent.match(/#([A-Z0-9-]{5,})/i)||[])[1];if(!code)return;try{const r=await fetch('/api/kasse-state',{cache:'no-store'});const d=await r.json();const o=(d.orders||[]).find(x=>String(x.externalOrderCode||'').toUpperCase()===code.toUpperCase());if(!o)return;parsed(o);const box=document.querySelector('#order-detail');if(!box||box.dataset.enhanced===code)return;const timelineEl=box.querySelector('.timeline');if(!timelineEl){box.insertAdjacentHTML('afterbegin',timeline(o));box.dataset.enhanced=code}const old=box.querySelector('.detail-contact');if(old&&o.__detail&&o.__detail.postal&&!old.textContent.includes(o.__detail.postal)){old.innerHTML='<b>'+esc2(o.delivery?.name||'Kunde')+'</b><br>'+esc2(o.__detail.phone||o.delivery?.phone||'')+'<br>'+esc2([o.__detail.street,o.delivery?.house,o.__detail.postal,o.__detail.city].filter(Boolean).join(' '))}}catch(e){}}
  setInterval(refreshDetail,1200); refreshDetail();
  document.querySelectorAll('.side-nav button').forEach((b,i)=>b.addEventListener('click',()=>{if(i===0)location.href='kasse.html';else if(i===1)location.reload();else if(i===2){const s=document.querySelector('#platform-filter');if(s){s.value='ALL';s.dispatchEvent(new Event('change'))}}else if(i===3)document.querySelector('[data-stage="HANDOVER"]')?.click();else if(i===4)document.querySelector('[data-stage="DONE"]')?.click();else window.scrollTo({top:0,behavior:'smooth'})}));
})();
