'use strict';
(function(){
 function init(){
  if(document.body.dataset.naraShell==='1')return;
  const header=document.querySelector('header');if(!header)return;document.body.dataset.naraShell='1';
  // اللغة: NARA_LANG إذا موجود، وإلا localStorage (de افتراضي)
  const lang=()=>{try{if(window.NARA_LANG?.get)return window.NARA_LANG.get()}catch(e){}for(const k of['nara-lang-app','nara-language']){try{const v=localStorage.getItem(k);if(['de','ar','en'].includes(v))return v}catch(e){}}return'de'};
  const L=(de,ar,en)=>({de,ar,en});
  const SOON=L('Demnächst','قريباً','Coming soon');
  const nav=[[L('Chef NARA · Kundenseite','Chef NARA · موقع الزبون','Chef NARA · Customer site'),'index.html#guide-dialog','customer-chef'],[L('Dashboard','لوحة التحكم','Dashboard'),'dashboard.html','dashboard'],[L('AI Manager','AI Manager','AI Manager'),'ai-control.html','ai-manager'],[L('Kasse','الكاشير','Cash register'),'kasse.html','kasse'],[L('Umsätze','المبيعات','Sales'),'sales.html','sales'],[L('Lieferaufträge','طلبات التوصيل','Delivery orders'),'driver-app-v2.html','delivery'],[L('Lieferzettel drucken','طباعة طلب توصيل','Print delivery slip'),'delivery-print.html','delivery-print'],[L('Verwaltung','الإدارة','Admin'),'admin-foundation.html','backend'],[L('Speisekarte','المنيو','Menu'),'admin-foundation.html','backend'],[L('Lager','المخزن','Stock'),'inventory-foundation.html#items','items'],[L('Lieferanten','الموردين','Suppliers'),'inventory-foundation.html#suppliers','suppliers'],[L('Einkaufsrechnungen','فواتير الشراء','Purchase invoices'),'inventory-foundation.html#invoices','invoices'],[L('Mitarbeiter & Schichten','الموظفين والورديات','Staff & shifts'),'staff.html','staff'],[L('Buchhaltung','المحاسبة','Accounting'),'accounting.html','accounting'],[L('Dokumente','الأوراق والمستندات','Documents'),'inventory-foundation.html#documents','documents'],[L('Rezepte','الوصفات','Recipes'),'javascript:void(0)','future'],[L('Berichte','التقارير','Reports'),'reports.html','reports'],[L('Einstellungen','الإعدادات','Settings'),'javascript:void(0)','future']];
  // كل رابط بياخد نصّو من هون (وبنرجع نحطّو بعد NARA_I18N لأنو بيكتب فوقو)
  function paint(){const l=lang();side.setAttribute('dir',l==='ar'?'rtl':'ltr');side.querySelectorAll('a[data-nav-idx]').forEach(a=>{const x=nav[+a.dataset.navIdx];if(!x)return;a.textContent=x[0][l]||x[0].de;if(x[2]==='future'){const sm=document.createElement('small');sm.textContent=' · '+(SOON[l]||SOON.de);a.append(sm)}})}
  function activeKey(){const p=location.pathname,h=location.hash;if(p.endsWith('dashboard.html'))return'dashboard';if(p.endsWith('ai-control.html'))return'ai-manager';if(p.endsWith('admin-foundation.html'))return'backend';if(p.endsWith('inventory-foundation.html'))return h.includes('suppliers')?'suppliers':h.includes('invoices')?'invoices':h.includes('documents')?'documents':'items';if(p.endsWith('kasse.html'))return'kasse';return''}
  const side=document.createElement('aside');side.className='side';side.innerHTML=nav.map((x,i)=>`<a data-nav-key="${x[2]}" data-nav-idx="${i}" class="${x[2]===activeKey()?'current':''}" href="${x[1]}"></a>`).join('');paint();
  const shell=document.createElement('div');shell.className='shell';const main=document.createElement('div');main.className='main';while(document.body.lastElementChild&&document.body.lastElementChild!==header)main.prepend(document.body.lastElementChild);const old=header.querySelector('a[href="kasse.html"],a[href="admin-foundation.html"]');if(old)old.style.display='none';const b=document.createElement('button');b.className='menu';b.textContent='☰';b.setAttribute('aria-label',{de:'Menü',ar:'القائمة',en:'Menu'}[lang()]||'Menü');b.onclick=()=>side.classList.toggle('open');header.prepend(b);document.body.append(shell);shell.append(side,main);
  function update(){const a=activeKey();side.querySelectorAll('[data-nav-key]').forEach(x=>x.classList.toggle('current',x.dataset.navKey===a));window.NARA_I18N?.apply();paint()}window.addEventListener('hashchange',update);window.addEventListener('popstate',update);window.NARA_I18N?.apply();paint();window.addEventListener('nara-language-changed',paint);window.addEventListener('nara-lang',paint)
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
 if(location.pathname.endsWith('sales.html')){const css=document.createElement('link');css.rel='stylesheet';css.href='nara-shell.css?v=20261002';document.head.append(css)}
})();
