'use strict';
(function(){
 function init(){
  if(document.body.dataset.naraShell==='1')return;
  const header=document.querySelector('header');if(!header)return;document.body.dataset.naraShell='1';
  const nav=[['Chef NARA · موقع الزبون','index.html#guide-dialog','customer-chef',''],['Dashboard','dashboard.html','dashboard','nav.dashboard'],['AI Manager','ai-control.html','ai-manager',''],['Kasse','kasse.html','kasse','nav.cashier'],['المبيعات','sales.html','sales',''],['طلبات التوصيل','driver-app-v2.html','delivery',''],['طباعة طلب توصيل','delivery-print.html','delivery-print',''],['Backend / Verwaltung','admin-foundation.html','backend','nav.backend'],['Menü','admin-foundation.html','backend','nav.menu'],['Lager','inventory-foundation.html#items','items','nav.storage'],['Lieferanten','inventory-foundation.html#suppliers','suppliers','nav.suppliers'],['Rechnungen شراء','inventory-foundation.html#invoices','invoices','nav.invoices'],['الموظفون والورديات','staff.html','staff',''],['المحاسبة','accounting.html','accounting',''],['Dokumente','inventory-foundation.html#documents','documents','nav.documents'],['Rezepte','javascript:void(0)','future','nav.recipes'],['Berberichte','reports.html','reports','nav.reports'],['Einstellungen','javascript:void(0)','future','nav.settings']];
  function activeKey(){const p=location.pathname,h=location.hash;if(p.endsWith('dashboard.html'))return'dashboard';if(p.endsWith('ai-control.html'))return'ai-manager';if(p.endsWith('admin-foundation.html'))return'backend';if(p.endsWith('inventory-foundation.html'))return h.includes('suppliers')?'suppliers':h.includes('invoices')?'invoices':h.includes('documents')?'documents':'items';if(p.endsWith('kasse.html'))return'kasse';return''}
  const side=document.createElement('aside');side.className='side';side.innerHTML=nav.map(x=>`<a data-nav-key="${x[2]}"${x[3]?` data-i18n="${x[3]}"`:''} class="${x[2]===activeKey()?'current':''}" href="${x[1]}">${x[0]}${x[2]==='future'?' <small>· Demnächst</small>':''}</a>`).join('');
  const shell=document.createElement('div');shell.className='shell';const main=document.createElement('div');main.className='main';while(document.body.lastElementChild&&document.body.lastElementChild!==header)main.prepend(document.body.lastElementChild);const old=header.querySelector('a[href="kasse.html"],a[href="admin-foundation.html"]');if(old)old.style.display='none';const b=document.createElement('button');b.className='menu';b.textContent='☰';b.onclick=()=>side.classList.toggle('open');header.prepend(b);document.body.append(shell);shell.append(side,main);
  function update(){const a=activeKey();side.querySelectorAll('[data-nav-key]').forEach(x=>x.classList.toggle('current',x.dataset.navKey===a));window.NARA_I18N?.apply()}window.addEventListener('hashchange',update);window.addEventListener('popstate',update);window.NARA_I18N?.apply();window.addEventListener('nara-language-changed',()=>window.NARA_I18N?.apply())
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
 if(location.pathname.endsWith('sales.html')){const css=document.createElement('link');css.rel='stylesheet';css.href='nara-shell.css?v=20261002';document.head.append(css)}
})();
