const $=id=>document.getElementById(id);
let employees=[],shifts=[],events=[],payroll=[];
const today=()=>new Date().toISOString().slice(0,10);
async function api(url,options){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok)throw Error(j.error||'تعذر تنفيذ العملية');return j;}
function money(cents){return `${(Number(cents||0)/100).toFixed(2)} €`;}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
async function load(){
  const date=$('payroll-date').value||today();
  [employees,shifts,events]=await Promise.all([api('/api/employees').then(x=>x.items),api('/api/shifts').then(x=>x.items),api('/api/attendance').then(x=>x.events)]);
  await loadPayroll(date);
  const open=shifts.filter(x=>x.status==='OPEN');
  $('summary-employees').textContent=employees.length;$('summary-shifts').textContent=open.length;$('summary-attendance').textContent=events.filter(x=>x.action==='CLOCK_IN'&&String(x.at||x.createdAt||'').slice(0,10)===date).length;
  $('employees').innerHTML=employees.length?employees.map(e=>{const s=shifts.find(x=>x.employeeId===e.id&&x.status==='OPEN');const present=events.some(x=>x.employeeId===e.id&&x.action==='CLOCK_IN'&&!x.closedAt);const internal=e.internalProfileEnabled!==false,official=e.officialProfileEnabled===true;return `<div class="employee-card"><div><h3>${esc(e.name)} <span class="workforce-badge internal">${internal?'داخلي مفعّل':'داخلي غير مفعّل'}</span> <span class="workforce-badge official">${official?'رسمي مفعّل':'رسمي غير مفعّل'}</span></h3><small>${esc(e.role)} · ${present?'حاضر الآن':'غير حاضر'} · ${s?'وردية مفتوحة':'لا توجد وردية'} · أجر الساعة: ${money(e.hourlyRateCents)}</small></div><div class="employee-actions"><button class="ghost" onclick="editEmployee('${e.id}')">تعديل</button><button class="${present?'active':''}" onclick="clock('${e.id}','${s?.id||''}')">${present?'تسجيل انصراف':'تسجيل حضور'}</button><button class="ghost" onclick="shift('${e.id}','${s?.id||''}')">${s?'إغلاق الوردية':'فتح وردية'}</button></div></div>`}).join(''):'لا يوجد موظفون بعد.';
  $('status').textContent=`${employees.length} موظف · ${open.length} وردية مفتوحة · ${events.length} سجل حضور`;
  $('shift-summary').innerHTML=open.length?open.map(s=>{const e=employees.find(x=>x.id===s.employeeId);return `<span>${esc(e?.name||s.employeeId)} · بدأت ${new Date(s.startAt).toLocaleString('ar-DE')}</span>`}).join(' | '):'لا توجد ورديات مفتوحة حالياً.';
}
async function loadPayroll(date=$('payroll-date').value||today()){ $('payroll-date').value=date;try{payroll=(await api(`/api/payroll/daily?date=${encodeURIComponent(date)}`)).rows||[];renderPayroll();}catch(e){$('payroll-table').textContent=e.message;throw e;} }
function renderPayroll(){if(!payroll.length){$('payroll-table').innerHTML='<div class="empty-state">لا توجد بيانات أجور لهذا اليوم بعد.</div>';return;}$('payroll-table').innerHTML=`<div class="payroll-head"><span>الموظف</span><span>الساعات</span><span>أجر الساعة</span><span>مستحق اليوم</span><span>سابق</span><span>المدفوع</span><span>الباقي</span><span>إجراء</span></div>${payroll.map(x=>`<div class="payroll-row"><strong>${esc(x.name)}</strong><span>${Number(x.hours||0).toFixed(2)}</span><span>${money(x.hourlyRateCents)}</span><span>${money(x.dailyDueCents)}</span><span>${money(x.carryCents)}</span><span>${money(x.paidCents)}</span><b class="${x.balanceCents>0?'due':''}">${money(x.balanceCents)}</b><button class="primary mini" onclick="payEmployee('${x.employeeId}',${x.balanceCents})">تسجيل دفع</button></div>`).join('')}`;}
function exportPayrollCsv(){if(!payroll.length){alert('لا توجد بيانات لتصديرها.');return;}const headers=['الموظف','التاريخ','الدخول بالدقائق','الاستراحة','ساعات العمل','أجر الساعة','مستحق اليوم','رصيد سابق','المدفوع','الباقي'];const rows=payroll.map(x=>[x.name,x.date,x.grossMinutes,x.breakMinutes,x.hours,(x.hourlyRateCents||0)/100,(x.dailyDueCents||0)/100,(x.carryCents||0)/100,(x.paidCents||0)/100,(x.balanceCents||0)/100]);const csv='\\ufeff'+[headers,...rows].map(row=>row.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\\r\\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`nara-payroll-${$('payroll-date').value||today()}.csv`;a.click();URL.revokeObjectURL(url);}
async function payEmployee(employeeId,balanceCents){if(balanceCents<=0){alert('لا يوجد مبلغ مستحق لهذا الموظف.');return;}const input=window.prompt(`المبلغ المدفوع حالياً (المتبقي ${money(balanceCents)}):`,(balanceCents/100).toFixed(2));if(input===null)return;const amountCents=Math.round(Number(input.replace(',','.'))*100);if(!Number.isInteger(amountCents)||amountCents<0||amountCents>balanceCents){alert('أدخل مبلغاً صحيحاً لا يتجاوز الباقي.');return;}await api('/api/payroll/settlements',{method:'POST',body:JSON.stringify({date:$('payroll-date').value||today(),employeeId,amountCents,method:'CASH',note:'تسوية يومية من شاشة الموظفين'})});await load();}
async function clock(id,shiftId){const present=events.some(x=>x.employeeId===id&&x.action==='CLOCK_IN'&&!x.closedAt);await api('/api/attendance',{method:'POST',body:JSON.stringify({employeeId:id,shiftId:shiftId||null,action:present?'CLOCK_OUT':'CLOCK_IN',source:'STAFF_SCREEN'})});load().catch(e=>alert(e.message));}
async function shift(id,shiftId){if(shiftId){await api(`/api/shifts/${encodeURIComponent(shiftId)}/close`,{method:'POST'});if(localStorage.getItem('nara-cashier-employee-id')===id)localStorage.removeItem('nara-cashier-employee-id');}else{await api('/api/shifts/open',{method:'POST',body:JSON.stringify({employeeId:id,openingCash:0})});localStorage.setItem('nara-cashier-employee-id',id);}load().catch(e=>alert(e.message));}
$('payroll-date').value=today();
$('payroll-date').addEventListener('change',()=>load().catch(e=>alert(e.message)));
function editEmployee(id){const e=employees.find(x=>x.id===id);if(!e)return;$('employee-id').value=e.id;$('name').value=e.name||'';$('role').value=e.role||'CASHIER';$('hourly-rate').value=((e.hourlyRateCents||0)/100).toFixed(2);$('contract-type').value=e.contractType||'HOURLY';$('profile-internal').checked=e.internalProfileEnabled!==false;$('profile-official').checked=e.officialProfileEnabled===true;$('break-minutes').value=e.breakMinutes||0;$('daily-deduction').value=((e.dailyDeductionCents||0)/100).toFixed(2);$('employee-submit').textContent='حفظ التعديل';$('cancel-edit').hidden=false;$('form-status').textContent=`تعديل بيانات: ${e.name}`;$('name').focus();}
function cancelEdit(){ $('employee-form').reset();$('employee-id').value='';$('break-minutes').value='0';$('daily-deduction').value='0';$('employee-submit').textContent='حفظ الموظف';$('cancel-edit').hidden=true;$('form-status').textContent='';}
 $('employee-form').addEventListener('submit',async e=>{e.preventDefault();try{const id=$('employee-id').value;const rate=Math.round(Number($('hourly-rate').value||0)*100);const payload={name:$('name').value,role:$('role').value,hourlyRateCents:rate,contractType:$('contract-type').value,internalProfileEnabled:$('profile-internal').checked,officialProfileEnabled:$('profile-official').checked,workforceType:$('profile-official').checked?'OFFICIAL':'INTERNAL',breakMinutes:Number($('break-minutes').value||0),dailyDeductionCents:Math.round(Number($('daily-deduction').value||0)*100),permissions:[]};await api(id?`/api/employees/${encodeURIComponent(id)}`:'/api/employees',{method:id?'PUT':'POST',body:JSON.stringify(payload)});cancelEdit();$('form-status').textContent=id?'تم تحديث بيانات الموظف.':'تم حفظ الموظف وأجر الساعة.';await load();}catch(err){$('form-status').textContent=err.message;}});
load().catch(e=>{$('employees').textContent=e.message;$('payroll-table').textContent=e.message;});
