'use strict';
(function(){
  const sentKey='nara-lieferando-live-sent-v2',clean=s=>String(s||'').replace(/\s+/g,' ').trim();
  const money=s=>{const m=String(s||'').match(/(?:Total|Gesamt)[\s\S]{0,120}?(?:EUR|€)\s*([0-9]+[,.][0-9]{2})/i)||String(s||'').match(/(?:EUR|€)\s*([0-9]+[,.][0-9]{2})/i);return m?Math.round(Number(m[1].replace(',','.'))*100):0};
  async function send(code,text,total){if(!code||!total)return;let sent=[];try{sent=(await chrome.storage.local.get(sentKey))[sentKey]||[]}catch{}const key=code+':'+total;if(sent.includes(key))return;const order={externalOrderCode:code,externalTotalCents:total,externalPaymentStatus:/online|paid|bezahlt/i.test(text)?'PAID_ON_PLATFORM':'UNKNOWN',type:/delivery|lieferung/i.test(text)?'delivery':'pickup',cart:[{id:'lieferando-'+code,name:'Lieferando order',quantity:1,unitCents:total,options:[],note:text}],rawText:text,source:'LIEFERANDO',platform:'Lieferando'};try{const result=await new Promise((resolve,reject)=>chrome.runtime.sendMessage({type:'NARA_IMPORT_LIEFERANDO',order},r=>chrome.runtime.lastError?reject(chrome.runtime.lastError):resolve(r)));if(!result?.ok)throw Error(result?.error||'bridge failed');await chrome.storage.local.set({[sentKey]:[...sent,key].slice(-1000)});console.info('[NARA][BRIDGE] imported',code)}catch(e){console.warn('[NARA][BRIDGE]',e.message)}}
  function scan(){const text=clean(document.body?.innerText||'');const codes=[...new Set([...text.matchAll(/#([A-Z0-9]{5,12})\b/gi)].map(m=>m[1].toUpperCase()))];for(const code of codes){const at=text.indexOf('#'+code);const chunk=text.slice(Math.max(0,at-250),Math.min(text.length,at+1800));const total=money(chunk);if(total)send(code,chunk,total)}console.info('[NARA][BRIDGE] page scan',codes.length,'orders')}
  const badge=document.createElement('div');badge.textContent='NARA bridge active';badge.style='position:fixed;bottom:8px;right:8px;z-index:2147483647;background:#0a7;color:#fff;padding:4px 7px;border-radius:4px;font:11px sans-serif;opacity:.8';document.documentElement.appendChild(badge);
  scan();new MutationObserver(()=>{clearTimeout(window.__naraBridgeTimer);window.__naraBridgeTimer=setTimeout(scan,500)}).observe(document.body,{childList:true,subtree:true,characterData:true});setInterval(scan,5000);
})();
