'use strict';
(function(){
  const sentKey='nara-lieferando-live-sent',clean=s=>String(s||'').replace(/\s+/g,' ').trim(),wait=ms=>new Promise(r=>setTimeout(r,ms));
  const money=s=>{const m=String(s||'').replace(',','.').match(/(?:EUR|€)\s*([0-9]+(?:\.[0-9]{1,2})?)/i)||String(s||'').match(/([0-9]+[,.][0-9]{2})\s*(?:EUR|€)/i);return m?Math.round(Number(m[1].replace(',','.'))*100):0};
  const identity=el=>{const text=clean(el?.innerText||el?.textContent||'');return {code:(text.match(/#([A-Z0-9]{5,12})\b/i)||[])[1]||'',text}};
  function parseCard(card){const {code,text}=identity(card),total=money(text.match(/(?:Total|Gesamt)[\s\S]{0,80}/i)?.[0]||text);if(!code||!total)return null;const items=[];for(const line of String(card.innerText||'').split(/\n/).map(clean)){const m=line.match(/^(\d+)\s+(.+?)\s+(?:EUR|€)\s*([0-9]+[,.][0-9]{2})$/i);if(m)items.push({name:m[2],quantity:+m[1],unitCents:Math.round(money(m[3])/+m[1])})}return {externalOrderCode:code,externalTotalCents:total,externalPaymentStatus:/online/i.test(text)?'PAID_ON_PLATFORM':'UNKNOWN',type:/delivery/i.test(text)?'delivery':'pickup',cart:items,rawText:text,source:'LIEFERANDO',platform:'Lieferando'}}
  async function send(order){const key=order.externalOrderCode+':'+order.externalTotalCents;let sent=[];try{sent=(await chrome.storage?.local?.get(sentKey))?.[sentKey]||[]}catch{}if(sent.includes(key))return;if(!order.cart.length)order.cart=[{id:'lieferando-'+order.externalOrderCode,name:'Lieferando order',quantity:1,unitCents:order.externalTotalCents,options:[],note:order.rawText}];const result=await new Promise((resolve,reject)=>{try{chrome.runtime.sendMessage({type:'NARA_IMPORT_LIEFERANDO',order},r=>chrome.runtime.lastError?reject(chrome.runtime.lastError):resolve(r))}catch(e){reject(e)}});if(!result?.ok)throw Error(result?.error||'NARA local bridge unavailable');try{await chrome.storage?.local?.set({[sentKey]:[...sent,key].slice(-500)})}catch{}console.info('[NARA][LIEFERANDO_BRIDGE] imported',order.externalOrderCode)}
  let busy=false,stopped=false;const report=e=>{if(/context invalidated|message port closed|receiving end/i.test(String(e?.message||e)))stopped=true;else console.warn('[NARA][LIEFERANDO_BRIDGE]',e?.message||e)};
  const clickable=el=>el.closest('button,[role="button"],a,[role="listitem"],article,li')||el;
  function candidates(){const seen=new Set(),out=[];for(const el of document.querySelectorAll('article,li,[role="listitem"],button,[role="button"],[class*="order" i],[class*="card" i]')){const id=identity(el);if(!id.code||seen.has(id.code)||id.text.length>1200)continue;const rect=el.getBoundingClientRect();if(rect.width<120||rect.height<35)continue;seen.add(id.code);out.push({el,code:id.code,text:id.text})}return out}
  function detailFor(code){const matches=[];for(const el of document.querySelectorAll('body *')){const id=identity(el);if(id.code!==code||id.text.length>1800||!/\b(?:Total|Gesamt)\b/i.test(id.text))continue;const rect=el.getBoundingClientRect();if(rect.width<120||rect.height<40)continue;matches.push(el)}matches.sort((a,b)=>(a.innerText||'').length-(b.innerText||'').length);return matches.length?parseCard(matches[0]):null}
  async function scan(){if(stopped||busy)return;busy=true;try{const list=candidates();console.info('[NARA][LIEFERANDO_BRIDGE] scan',list.map(x=>x.code));for(const candidate of list){if(stopped)break;const known=candidate.code;let order=parseCard(candidate.el)||detailFor(known);if(!order){const target=clickable(candidate.el);console.info('[NARA][LIEFERANDO_BRIDGE] opening',known,target.tagName,target.className||'');target.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));await wait(1100);order=detailFor(known)}if(order)await send(order).catch(report);else console.warn('[NARA][LIEFERANDO_BRIDGE] no readable detail for',known)}}catch(e){report(e)}finally{busy=false}}
  scan();setInterval(scan,7000);console.info('[NARA][LIEFERANDO_BRIDGE] auto-reading live orders');
})();
